// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzco6IezL_MshCya_6gVgxUDrwXF7nmD8',
    appId: '1:975949379453:web:32acd8f73ab81110643e14',
    messagingSenderId: '975949379453',
    projectId: 'shopapp-821ac',
    authDomain: 'shopapp-821ac.firebaseapp.com',
    storageBucket: 'shopapp-821ac.appspot.com',
    measurementId: 'G-6WRT6L4FPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfzf-hxU86n7ceBjwPzlg-VxOZztsuc-Q',
    appId: '1:975949379453:android:d3d276acfc4355f3643e14',
    messagingSenderId: '975949379453',
    projectId: 'shopapp-821ac',
    storageBucket: 'shopapp-821ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_tXOtUV2o0rqvAgC65tJ0jP_iaRY6lZk',
    appId: '1:975949379453:ios:d862d94fbdded642643e14',
    messagingSenderId: '975949379453',
    projectId: 'shopapp-821ac',
    storageBucket: 'shopapp-821ac.appspot.com',
    iosClientId: '975949379453-44gl0go3hb14g3cghkr6ma9reljh9da8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_tXOtUV2o0rqvAgC65tJ0jP_iaRY6lZk',
    appId: '1:975949379453:ios:d862d94fbdded642643e14',
    messagingSenderId: '975949379453',
    projectId: 'shopapp-821ac',
    storageBucket: 'shopapp-821ac.appspot.com',
    iosClientId: '975949379453-44gl0go3hb14g3cghkr6ma9reljh9da8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
